name: Build Docker Images

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Version
        run: echo "VERSION=$(head -n 1 VERSION)" >> ${GITHUB_ENV}
      - name: Lowercase the server container image name
        run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}
      - name: Log in to the container registry
        uses: docker/login-action@v3 # ref: https://github.com/marketplace/actions/docker-login
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Django
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/django/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_django:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_django:latest
      - name: Build and push Postgres
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/postgres/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_postgres:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_postgres:latest
      - name: Build and push Nginx
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/nginx/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_nginx:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_nginx:latest
      - name: Build and push Redis
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/redis/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_redis:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_redis:latest
      - name: Build and push Hasura
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/hasura/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_hasura:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_hasura:latest
      - name: Build and push Collab Server
        uses: docker/build-push-action@v6
        with:
          file: ./compose/production/collab-server/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_collab_server:${{env.VERSION}}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/ghostwriter_collab_server:latest
